/**
 * Post-sync notifications:
 *  1. Admin report — roster users not found in Slack, posted to SLACK_ADMIN_REPORT_CHANNEL
 *  2. DM to unregistered — Slack members with no roster entry, asked to sign up to SSO
 *
 * Dev mode: set DEV_SLACKUSER to an email address to restrict DMs to that one user only.
 */
import type { WebClient } from '@slack/web-api';
import type { SyncReport } from './sync';

export async function sendPostSyncNotifications(
  client: WebClient,
  report: SyncReport,
): Promise<void> {
  await Promise.allSettled([
    sendAdminReport(client, report),
    notifyUnregisteredUsers(client, report),
  ]);
}

async function sendAdminReport(client: WebClient, report: SyncReport): Promise<void> {
  const raw = process.env.SLACK_ADMIN_REPORT_CHANNEL;
  if (!raw) return;
  // Channel IDs (C...) are used as-is; names get a # prefix
  const channel = raw.startsWith('C') ? raw : `#${raw}`;

  if (report.inSlackNotRoster.length === 0) return;

  const lines = report.inSlackNotRoster.map((m) =>
    `• <@${m.id}> (${m.email ?? m.username})`,
  );

  await client.chat.postMessage({
    channel,
    text: `*Slack members not in SSO roster* (${report.inSlackNotRoster.length})`,
    blocks: [
      {
        type: 'header',
        text: { type: 'plain_text', text: 'Slack members not in SSO roster' },
      },
      {
        type: 'section',
        text: { type: 'mrkdwn', text: lines.join('\n') },
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `${report.inSlackNotRoster.length} user(s) · Generated by E4E Roster Bot`,
          },
        ],
      },
    ],
  });

  console.log(`[notify] admin report sent to ${channel}`);
}

async function notifyUnregisteredUsers(client: WebClient, report: SyncReport): Promise<void> {
  if (report.inSlackNotRoster.length === 0) return;

  const devFilter = process.env.DEV_SLACKUSER?.toLowerCase();

  const targets = devFilter
    ? report.inSlackNotRoster.filter((m) => m.email?.toLowerCase() === devFilter)
    : report.inSlackNotRoster;

  if (devFilter) {
    console.log(`[notify] DEV_SLACKUSER set — restricting DMs to ${devFilter} (${targets.length} match)`);
  }

  for (const member of targets) {
    try {
      const { channel } = await client.conversations.open({ users: member.id });
      if (!channel?.id) continue;

      await client.chat.postMessage({
        channel: channel.id,
        text: `Hi ${member.realName || member.username} 👋`,
        blocks: [
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text:
                `Hi ${member.realName || member.username} :wave:\n\n` +
                `You're in the E4E Slack workspace but don't have an SSO account set up yet. ` +
                `An SSO account lets you access lab resources, servers, and keeps your membership on record.\n\n` +
                `Please reach out to a Project Lead or staff member to get set up.`,
            },
          },
        ],
      });

      console.log(`[notify] DM sent to unregistered user ${member.username} (${member.email ?? 'no email'})`);
    } catch (err) {
      console.error(`[notify] failed to DM ${member.username}:`, err);
    }
  }
}
