import React from 'react';
import { Link, Outlet, isRouteErrorResponse, useLoaderData, useRouteError } from 'react-router';
import type { LocalAdminSummary, SystemAuditEntry, SystemGroupProvisioningOptions, SystemLdapMappingWorkspace, SystemOrganization, SystemProvisionResult, SystemUiContext, SystemUserEdit, SystemUserSummary } from './system.server';

export function SystemShell(): React.JSX.Element {
  const { context } = useLoaderData() as { context: SystemUiContext };
  return <html lang="en" data-theme="dark"><head>
    <meta charSet="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>System administration — Roster</title><link rel="stylesheet" href="/static/css/react-roster.css" />
    <script src="/static/js/react-roster-theme.js" defer />
  </head><body><div className="workspace-shell system-shell"><header className="workspace-header">
    <Link to="/local-admins" className="brand-mark"><span><strong>Roster System</strong><small>Administration</small></span></Link>
    <nav aria-label="System administration navigation"><Link to="/local-admins">Local admins</Link><Link to="/users">Users</Link><Link to="/groups/new">Groups</Link><Link to="/organizations">Organizations</Link><Link to="/audit">Audit log</Link></nav>
    <div className="account-cluster"><span>{context.user.name || context.user.username}</span><button className="theme-toggle" id="theme-toggle" type="button">Light mode</button><a href="/orgs">My orgs</a></div>
  </header><main className="workspace-main"><Outlet /></main></div></body></html>;
}

type SystemUserFormProps = { groups: string[]; user?: SystemUserEdit; actionLabel: string; cancelTo: string };

function SystemUserForm({ groups, user, actionLabel, cancelTo }: SystemUserFormProps): React.JSX.Element {
  return <section className="form-card person-form-card"><form className="workspace-form" method="post"><div className="form-section"><h2>Basic information</h2><div className="form-two-column"><label>First name<input name="firstName" required defaultValue={user?.firstName ?? ''} autoComplete="off" /></label><label>Last name<input name="lastName" required defaultValue={user?.lastName ?? ''} autoComplete="off" /></label></div><label>Institutional email<input name="email" type="email" required defaultValue={user?.email ?? ''} autoComplete="off" /></label><label>Long-term email <span className="form-optional">optional</span><input name="secondaryEmail" type="email" defaultValue={user?.secondaryEmail ?? ''} /></label><label>Phone <span className="form-optional">optional</span><input name="phone" type="tel" defaultValue={user?.phone ?? ''} /></label></div><div className="form-section"><h2>Account</h2><div className="form-two-column"><label>Role<select name="role" required defaultValue={user?.role ?? ''}><option value="" disabled>Choose a role</option><option value="student">Student</option><option value="researcher">Researcher</option><option value="staff">Staff</option><option value="alumni">Alumni</option></select></label><label>Expiry date<input name="expiryDate" type="date" required defaultValue={user?.expiryDate ?? ''} /></label></div></div><div className="form-section"><h2>Directory groups</h2><p className="form-copy">System administrators may manage all directory groups.</p>{groups.length ? <div className="check-grid form-check-grid">{groups.map((group) => <label key={group}><input type="checkbox" name={user ? 'groups' : 'ldapGroups'} value={group} defaultChecked={user?.ldapGroups.includes(group)} /> {group}</label>)}</div> : <p className="empty-inline">Directory groups are unavailable. Check the directory connection before saving.</p>}</div><label>SSH public keys <span className="form-optional">one per line; replaces existing keys</span><textarea name="sshKeys" rows={4} defaultValue={user?.sshPublicKeys.join('\n') ?? ''} /></label><div className="form-section"><h2>Integrations <span className="form-optional">optional</span></h2><div className="form-two-column"><label>GitHub username<input name="githubUsername" defaultValue={user?.githubUsername ?? ''} /></label><label>Slack username<input name="slackUsername" defaultValue={user?.slackUsername ?? ''} /></label></div></div><div className="form-actions"><button className="button primary" type="submit">{actionLabel}</button><Link className="button secondary" to={cancelTo}>Cancel</Link></div></form></section>;
}

export function SystemUserCreatePage(): React.JSX.Element {
  const { groups } = useLoaderData() as { groups: string[]; context: SystemUiContext };
  return <><Link to="/users" className="back-link">← Directory users</Link><section className="hero-row project-hero"><div><p className="eyebrow">System administration</p><h1>Create directory user</h1><p className="lede">Create the LDAP account, optional SSH keys, and the roster record in one controlled operation.</p></div></section><SystemUserForm groups={groups} actionLabel="Create directory user" cancelTo="/users" /></>;
}

export function SystemUserProvisionResultPage(): React.JSX.Element {
  const { result } = useLoaderData() as { result: SystemProvisionResult; context: SystemUiContext };
  const created = result.ldapStatus === 'success' || result.ldapStatus === 'already_exists';
  return <><Link to="/users" className="back-link">← Directory users</Link><section className="content-card provision-result"><p className="eyebrow">Directory provisioning</p><h1>{created ? 'Directory user ready' : 'Directory user was not created'}</h1><p className="lede">{result.ldapMessage}</p><dl className="account-details"><dt>Username</dt><dd><code>{result.username}</code></dd><dt>Email</dt><dd>{result.email}</dd></dl>{result.tempPassword && <section className="temporary-password"><h2>Temporary password</h2><p>Copy this now. It is displayed once and is not included in a URL or audit record.</p><code>{result.tempPassword}</code></section>}{result.sshResults.length > 0 && <section><h2>SSH keys</h2><ul>{result.sshResults.map((entry, index) => <li key={index}><code>{entry.preview}</code> — {entry.message}</li>)}</ul></section>}<div className="form-actions"><Link className="button primary" to="/users">Return to directory users</Link>{created && <Link className="button secondary" to={`/users/${result.username}/edit`}>Manage user</Link>}</div></section></>;
}

export function SystemUserEditPage(): React.JSX.Element {
  const { user, groups } = useLoaderData() as { user: SystemUserEdit; groups: string[]; context: SystemUiContext };
  const displayName = [user.firstName, user.lastName].filter(Boolean).join(' ') || user.username;
  return <><Link to="/users" className="back-link">← Directory users</Link><section className="hero-row project-hero"><div><p className="eyebrow">System administration</p><h1>{displayName}</h1><p className="lede">Manage this directory account across every organization.</p></div></section><SystemUserForm groups={groups} user={user} actionLabel="Save directory user" cancelTo="/users" /></>;
}

export function SystemGroupProvisionPage(): React.JSX.Element {
  const { options } = useLoaderData() as { options: SystemGroupProvisioningOptions; context: SystemUiContext };
  return <><Link to="/organizations" className="back-link">← Organizations</Link><section className="hero-row project-hero"><div><p className="eyebrow">System administration</p><h1>Create directory group</h1><p className="lede">Provision an LDAP group and optionally connect it to organizations, a project, and integration destinations.</p></div></section><section className="form-card person-form-card"><form className="workspace-form" method="post"><div className="form-section"><h2>Directory group</h2><label>Group name<input name="groupName" required pattern="[A-Za-z0-9._-]+" placeholder="e.g. exploration-team" autoComplete="off" /><span className="form-hint">Letters, numbers, periods, underscores, and hyphens only.</span></label></div><div className="form-section"><h2>Organization availability</h2><p className="form-copy">Choose every organization where this group should be selectable on a roster or project.</p>{options.organizations.length ? <div className="check-grid form-check-grid">{options.organizations.map((organization) => <label key={organization.id}><input type="checkbox" name="orgIds" value={organization.id} /> {organization.name}</label>)}</div> : <p className="empty-inline">No organizations exist yet.</p>}</div><div className="form-section"><h2>Project <span className="form-optional">optional</span></h2><label>Assign to project<select name="projectId" defaultValue=""><option value="">No project</option>{options.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label></div><div className="form-section"><h2>Integrations <span className="form-optional">optional</span></h2><label>GitHub team<select name="githubTeam" defaultValue=""><option value="">No GitHub team</option>{options.githubTeams.map((team) => <option key={team.slug} value={`${team.slug}|${team.name}`}>{team.name}</option>)}</select></label><label>Slack channel<select name="slackChannel" defaultValue=""><option value="">No Slack channel</option>{options.slackChannels.map((channel) => <option key={channel.id} value={`${channel.id}|${channel.name}`}>{channel.name}</option>)}</select></label><p className="form-copy">Integration options appear when their local service is reachable. Configure mappings later if needed.</p></div><div className="form-actions"><button className="button primary" type="submit">Create directory group</button><Link className="button secondary" to="/organizations">Cancel</Link></div></form></section></>;
}

export function SystemUsersPage(): React.JSX.Element {
  const { users, sync } = useLoaderData() as { users: SystemUserSummary[]; sync: string | null; context: SystemUiContext };
  return <><section className="hero-row project-hero"><div><p className="eyebrow">System administration</p><h1>Directory users</h1><p className="lede">A cross-organization directory view with controlled LDAP-backed account creation and editing.</p></div><div className="project-actions"><form method="post"><input type="hidden" name="intent" value="sync" /><button className="button secondary" type="submit">Sync directory</button></form><Link className="button primary" to="/users/new">Create directory user</Link></div></section>{sync && <p className="save-notice" role="status">Directory sync complete — {sync.split(',')[0]} updated, {sync.split(',')[1]} removed, {sync.split(',')[2]} errors.</p>}
    <section className="content-card"><div className="section-heading"><div><p className="eyebrow">Directory</p><h2>{users.length} {users.length === 1 ? 'user' : 'users'}</h2></div><p>Directory groups are shown for diagnosis; organization membership is managed separately.</p></div>{users.length === 0 ? <div className="empty-state compact"><h2>No directory users</h2><p>Create the first account from this workspace.</p></div> : <div className="table-wrap"><table><thead><tr><th>Person</th><th>Role</th><th>LDAP groups</th><th>Status</th><th></th></tr></thead><tbody>{users.map((user) => { const name = [user.firstName, user.lastName].filter(Boolean).join(' ') || user.username; return <tr key={user.username}><td><strong>{name}</strong><small>{user.username} · {user.email || 'No email'}</small></td><td>{user.role || '—'}</td><td><div className="tag-row table-tags">{user.ldapGroups.map((group) => <span className="tag small" key={group}>{group}</span>)}</div></td><td><span className={`status ${user.disabled ? 'disabled' : 'active'}`}>{user.disabled ? 'Disabled' : 'Active'}</span></td><td><Link className="row-link" to={`/users/${user.username}/edit`}>Manage</Link></td></tr>; })}</tbody></table></div>}</section></>;
}

export function SystemAuditPage(): React.JSX.Element {
  const { audit } = useLoaderData() as { audit: { days: number; entries: SystemAuditEntry[] }; context: SystemUiContext };
  return <><section className="hero-row project-hero"><div><p className="eyebrow">System administration</p><h1>Audit log</h1><p className="lede">Up to 1,000 system and roster events from the last {audit.days} day{audit.days === 1 ? '' : 's'}.</p></div><form className="audit-range" method="get"><label>Time range<select name="days" defaultValue={audit.days}><option value="1">1 day</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label><button className="button secondary" type="submit">Apply</button></form></section>
    <section className="content-card">{audit.entries.length === 0 ? <div className="empty-state compact"><h2>No recent events</h2><p>No audit entries were recorded during this time range.</p></div> : <div className="table-wrap"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Organization</th><th>Details</th></tr></thead><tbody>{audit.entries.map((entry) => <tr key={entry.id}><td><small>{entry.createdAt}</small></td><td><code>{entry.actor}</code></td><td><span className="tag small">{entry.action.replace(/_/g, ' ')}</span></td><td>{entry.targetUsername ? <code>{entry.targetUsername}</code> : '—'}</td><td>{entry.orgName && entry.orgSlug ? <a className="row-link" href={`/orgs/${entry.orgSlug}/v2/dashboard`}>{entry.orgName}</a> : '—'}</td><td className="audit-details">{entry.details ? <details><summary>View details</summary><pre>{formatAuditDetails(entry.details)}</pre></details> : '—'}</td></tr>)}</tbody></table></div>}</section></>;
}

function formatAuditDetails(raw: unknown): string {
  if (typeof raw === 'string') {
    try { return JSON.stringify(JSON.parse(raw), null, 2); } catch { return raw; }
  }
  return JSON.stringify(raw, null, 2);
}

export function SystemLdapMappingsPage(): React.JSX.Element {
  const { mappings, synced } = useLoaderData() as { mappings: SystemLdapMappingWorkspace; synced: string | null; context: SystemUiContext };
  const { organization, availableGroups } = mappings;
  return <><Link to="/organizations" className="back-link">← Organizations</Link><section className="hero-row project-hero"><div><p className="eyebrow">System administration</p><h1>{organization.name} LDAP mappings</h1><p className="lede">Map directory groups to organization roles. A member in multiple groups receives the highest mapped role.</p></div><form method="post"><input type="hidden" name="intent" value="sync" /><button className="button primary" type="submit">Sync members</button></form></section>
    {synced !== null && <p className="save-notice" role="status">Sync complete — {synced} {synced === '1' ? 'person' : 'people'} added or updated.</p>}
    <div className="system-split"><section className="content-card"><div className="section-heading"><div><p className="eyebrow">Role mappings</p><h2>{mappings.mappings.length} {mappings.mappings.length === 1 ? 'mapping' : 'mappings'}</h2></div><p>Utility groups remain available to the organization but do not grant membership.</p></div>{mappings.mappings.length === 0 ? <div className="empty-state compact"><h2>No mappings yet</h2><p>Add a directory group to enable automatic organization membership.</p></div> : <div className="table-wrap"><table><thead><tr><th>LDAP group</th><th>Role</th><th></th></tr></thead><tbody>{mappings.mappings.map((mapping) => <tr key={mapping.id}><td><code>{mapping.ldapGroup}</code></td><td><form className="inline-form" method="post"><input type="hidden" name="intent" value="role" /><input type="hidden" name="mappingId" value={mapping.id} /><select name="role" defaultValue={mapping.role}><option value="member">Member</option><option value="project_lead">Project lead</option><option value="org_admin">Organization admin</option><option value="utility">Utility</option></select><button className="row-link action-link" type="submit">Save</button></form></td><td><form method="post"><input type="hidden" name="intent" value="delete" /><input type="hidden" name="mappingId" value={mapping.id} /><button className="danger-link" type="submit">Remove</button></form></td></tr>)}</tbody></table></div>}</section>
      <section className="form-card"><form className="workspace-form" method="post"><input type="hidden" name="intent" value="add" /><p className="eyebrow">Directory access</p><h2>Add mapping</h2><label>LDAP group {availableGroups.length > 0 ? <select name="ldapGroup" required defaultValue=""><option value="" disabled>Choose a directory group</option>{availableGroups.map((group) => <option key={group} value={group}>{group}</option>)}</select> : <input name="ldapGroup" required placeholder="directory-group-name" autoComplete="off" />}</label><p className="form-copy">{availableGroups.length > 0 ? 'Groups already mapped here are hidden.' : 'Directory lookup is unavailable; enter the exact LDAP group name.'}</p><label>Organization role<select name="role" defaultValue="member"><option value="member">Member</option><option value="project_lead">Project lead</option><option value="org_admin">Organization admin</option><option value="utility">Utility (no membership)</option></select></label><button className="button primary" type="submit">Add mapping</button></form></section></div></>;
}

export function SystemOrganizationsPage(): React.JSX.Element {
  const { organizations } = useLoaderData() as { organizations: SystemOrganization[]; context: SystemUiContext };
  return <><section className="hero-row project-hero"><div><p className="eyebrow">System administration</p><h1>Organizations</h1><p className="lede">Create workspaces, set their visual identity, and manage their membership mappings.</p></div></section>
    <div className="system-split"><section className="content-card"><div className="section-heading"><div><p className="eyebrow">Workspaces</p><h2>{organizations.length} {organizations.length === 1 ? 'organization' : 'organizations'}</h2></div><p>Each organization owns its projects, roster metadata, and integrations.</p></div>{organizations.length === 0 ? <div className="empty-state compact"><h2>No organizations</h2><p>Create the first organization to begin configuring the roster.</p></div> : <div className="table-wrap"><table><thead><tr><th>Name</th><th>Slug</th><th>Members</th><th>Theme</th><th>Actions</th></tr></thead><tbody>{organizations.map((organization) => <tr key={organization.id}><td><strong>{organization.name}</strong><small>{organization.description || 'No description'}</small></td><td><code>{organization.slug}</code></td><td>{organization.memberCount}</td><td><form method="post" className="inline-form"><input type="hidden" name="intent" value="theme" /><input type="hidden" name="id" value={organization.id} /><input aria-label={`Theme for ${organization.name}`} type="color" name="themeColor" defaultValue={organization.themeColor || '#182B49'} /><button className="row-link action-link" type="submit">Save</button></form></td><td><div className="row-actions"><Link className="row-link" to={`/organizations/${organization.id}/mappings`}>Mappings</Link><form method="post"><input type="hidden" name="intent" value="delete" /><input type="hidden" name="id" value={organization.id} /><label className="confirm-check"><input type="checkbox" name="confirm" value="delete" /> Confirm</label><button className="danger-link" type="submit">Delete</button></form></div></td></tr>)}</tbody></table></div>}</section>
      <section className="form-card"><form className="workspace-form" method="post"><p className="eyebrow">New workspace</p><h2>Create organization</h2><input type="hidden" name="intent" value="create" /><label>Name<input name="name" required placeholder="e.g. Engineers for Exploration" /></label><label>Slug <span className="form-optional">used in URLs</span><input name="slug" required pattern="[a-z0-9-]+" placeholder="e.g. e4e" /></label><label>Description <span className="form-optional">optional</span><textarea name="description" rows={3} /></label><label>Theme color<input type="color" name="themeColor" defaultValue="#182B49" /></label><button className="button primary" type="submit">Create organization</button></form></section></div></>;
}

export function SystemLocalAdminsPage(): React.JSX.Element {
  const { admins } = useLoaderData() as { admins: LocalAdminSummary[]; context: SystemUiContext };
  return <><section className="hero-row project-hero"><div><p className="eyebrow">System administration</p><h1>Local admins</h1><p className="lede">Break-glass accounts for recovery while single sign-on is unavailable. Remove them when they are no longer needed.</p></div></section>
    <div className="system-split"><section className="content-card"><div className="section-heading"><div><p className="eyebrow">Emergency access</p><h2>{admins.length} {admins.length === 1 ? 'account' : 'accounts'}</h2></div><p>These credentials bypass normal organization membership checks.</p></div>{admins.length === 0 ? <div className="empty-state compact"><h2>No local admins</h2><p>SSO is currently the only administrator sign-in path.</p></div> : <div className="table-wrap"><table><thead><tr><th>Username</th><th>Status</th><th>Last used</th><th>Actions</th></tr></thead><tbody>{admins.map((admin) => <tr key={admin.id}><td><strong><code>{admin.username}</code></strong></td><td><span className={`status ${admin.enabled ? 'active' : 'disabled'}`}>{admin.enabled ? 'Enabled' : 'Disabled'}</span></td><td>{admin.lastUsedAt || 'Never'}</td><td><div className="row-actions"><form method="post"><input type="hidden" name="intent" value="toggle" /><input type="hidden" name="id" value={admin.id} /><button className="row-link action-link" type="submit">{admin.enabled ? 'Disable' : 'Enable'}</button></form><form method="post"><input type="hidden" name="intent" value="delete" /><input type="hidden" name="id" value={admin.id} /><label className="confirm-check"><input type="checkbox" name="confirm" value="delete" /> Confirm</label><button className="danger-link" type="submit">Delete</button></form></div></td></tr>)}</tbody></table></div>}</section>
      <section className="form-card"><form className="workspace-form" method="post"><p className="eyebrow">Recovery</p><h2>Create local admin</h2><p className="form-copy">Store this credential securely. Creating an existing username resets its password and enables it.</p><input type="hidden" name="intent" value="create" /><label>Username<input name="username" required autoComplete="off" /></label><label>Password<input type="password" name="password" required autoComplete="new-password" /></label><button className="button primary" type="submit">Create local admin</button></form></section></div></>;
}

export function SystemRouteError(): React.JSX.Element {
  const error = useRouteError();
  const message = isRouteErrorResponse(error) ? String(error.data) : 'Something went wrong while loading system administration.';
  return <div className="standalone-error"><h1>System administration unavailable</h1><p>{message}</p><a href="/system/v2/local-admins">Return to local admins</a></div>;
}
